---
- name: "Install packages Tuned"
  hosts: servers
  become: yes
  tasks:
  
  - name: "Required packages"
    apt:
      name:
        - tuned
        - tuned-utils
        - tuned-utils-systemtap
      state: latest
      
  - name: "Start tuned"
    systemd:
      name: tuned
      state: started
      enabled: yes
...