---
- name: "Editing the motd file"
  hosts: servers
  become: yes
  tasks:

  - name: "Add line to motd file"
    lineinfile: dest=/etc/motd
                regexp='^'
                line='\n#Distribution kit for executing Netology tasks.'
                state=present
...